[package]
name = "demo"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
dioxus = { version = "0.7.9", features = ["desktop"] }
plotters = { version = "0.3.7" }
plotters-dioxus = { path = "../plotters-dioxus", default-features = false, features = ["bitmap"] }

rand = "0.10.0"
rand_distr = "0.6.0"
rand_xorshift = "0.5.0"
